declare namespace Express {
    /**
     * Represents custom Express Request object type containing an authorized account fields (name and email).
     */
    export interface Request {
        authorizedAccount?: {
            name: string;
            email: string;
        };
    }
}

declare namespace Test {
    /**
     * Represents object type for an Account with random data generated by a factory.
     */
    export interface Account {
        name: string;
        email: string;
        password: string;
    }
}

/**
 * Represents an object type for template email's delivery fields and content.
 */
interface MailOptions {
    to: {
        name: string;
        email: string;
    };
    from: {
        name: string;
        email: string;
    };
    subject: string;
    template: string;
    content?: object;
}

/**
 * Represents object type for an API error.
 */
interface APIError {
    code: number;
    message: string;
    internalMessage: string;
}
/**
 * Represents object type for an Express Request validator.
 */
interface RequestValidator {
    name: string;
    schema: object;
}
